
####################################################################################
# Generated by Vivado 2014.4 built on 'Tue Nov 18 18:29:27 MST 2014' by 'xbuild'
# Command Used: write_xdc -force C:/Chandler/proj/hw_sh/20130729_esu/pr_demo/constraint/pblock1.xdc
####################################################################################


set_property HD.RECONFIGURABLE true [get_cells {u_ul_pr_top}]

current_instance -quiet
create_pblock pblock_u_ul_pr_top
add_cells_to_pblock [get_pblocks pblock_u_ul_pr_top] [get_cells -quiet [list u_ul_pr_top]]
resize_pblock [get_pblocks pblock_u_ul_pr_top] -add {CLOCKREGION_X0Y0:CLOCKREGION_X5Y14}
resize_pblock [get_pblocks pblock_u_ul_pr_top] -remove {CLOCKREGION_X3Y4:CLOCKREGION_X5Y9}
set_property RESET_AFTER_RECONFIG true [get_pblocks pblock_u_ul_pr_top]
set_property SNAPPING_MODE ON [get_pblocks pblock_u_ul_pr_top]

